let a=15;
for(i=1;i<=a;i++)
{ 
    if((i%3==0)&&(i%5==0))
        {
            console.log("Fizzbuzz");
        }
        else   
            if(i%5==0)
            {
             console.log("Buzz");
            }
        else
            if(i%3==0)
            {
             console.log("fizz");
            }
            else
            console.log("nothing");
}